import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils';

export const MAX_QUERY_TABS = 10;

const scope = '/Components/organisms/MongodbWorkbench/';

export const REDUCER_KEY = `${CURRENT_APP_NAME}_mongodbWorkbench`;

export const actionTypes = defineActionTypes(
  {
    GET_ORG_DBS_REQUEST: 'GET_ORG_DBS_REQUEST',
    GET_ORG_DBS_SUCCESS: 'GET_ORG_DBS_SUCCESS',
    GET_ORG_DBS_FAILURE: 'GET_ORG_DBS_FAILURE',

    GET_DB_COLLECTIONS_REQUEST: 'GET_DB_COLLECTIONS_REQUEST',
    GET_DB_COLLECTIONS_SUCCESS: 'GET_DB_COLLECTIONS_SUCCESS',
    GET_DB_COLLECTIONS_FAILURE: 'GET_DB_COLLECTIONS_FAILURE',

    EXECUTE_MONGO_QUERY_REQUEST: 'EXECUTE_MONGO_QUERY_REQUEST',
    EXECUTE_MONGO_QUERY_SUCCESS: 'EXECUTE_MONGO_QUERY_SUCCESS',
    EXECUTE_MONGO_QUERY_FAILURE: 'EXECUTE_MONGO_QUERY_FAILURE',
    RESET_MONGO_QUERY: 'RESET_MONGO_QUERY',

    GET_MONGO_SCHEMA_REQUEST: 'GET_MONGO_SCHEMA_REQUEST',
    GET_MONGO_SCHEMA_SUCCESS: 'GET_MONGO_SCHEMA_SUCCESS',
    GET_MONGO_SCHEMA_FAILURE: 'GET_MONGO_SCHEMA_FAILURE',
    CLEAR_MONGO_SCHEMA: 'CLEAR_MONGO_SCHEMA',
  },
  { prefix: CURRENT_APP_NAME, scope },
);
