import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils';

const scope = '/Components/organisms/ExtensionsDeployment/';

export const REDUCER_KEY = `${CURRENT_APP_NAME}_extensionsDeployment`;

export const actionTypes = defineActionTypes(
  {
    GET_EXTENSIONS_BUILD_HISTORY_REQUEST: 'GET_EXTENSIONS_BUILD_HISTORY_REQUEST',
    GET_EXTENSIONS_BUILD_HISTORY_SUCCESS: 'GET_EXTENSIONS_BUILD_HISTORY_SUCCESS',
    GET_EXTENSIONS_BUILD_HISTORY_FAILURE: 'GET_EXTENSIONS_BUILD_HISTORY_FAILURE',

    GET_EXTENSIONS_BUILD_LOGS_REQUEST: 'GET_EXTENSIONS_BUILD_LOGS_REQUEST',
    GET_EXTENSIONS_BUILD_LOGS_SUCCESS: 'GET_EXTENSIONS_BUILD_LOGS_SUCCESS',
    GET_EXTENSIONS_BUILD_LOGS_FAILURE: 'GET_EXTENSIONS_BUILD_LOGS_FAILURE',
    CLEAR_EXTENSIONS_BUILD_LOGS: 'CLEAR_EXTENSIONS_BUILD_LOGS',

    GET_EXTENSIONS_BUILD_META_REQUEST: 'GET_EXTENSIONS_BUILD_META_REQUEST',
    GET_EXTENSIONS_BUILD_META_SUCCESS: 'GET_EXTENSIONS_BUILD_META_SUCCESS',
    GET_EXTENSIONS_BUILD_META_FAILURE: 'GET_EXTENSIONS_BUILD_META_FAILURE',

    TRIGGER_EXTENSIONS_BUILD_REQUEST: 'TRIGGER_EXTENSIONS_BUILD_REQUEST',
    TRIGGER_EXTENSIONS_BUILD_SUCCESS: 'TRIGGER_EXTENSIONS_BUILD_SUCCESS',
    TRIGGER_EXTENSIONS_BUILD_FAILURE: 'TRIGGER_EXTENSIONS_BUILD_FAILURE',
    RESET_TRIGGER_EXTENSIONS_BUILD: 'RESET_TRIGGER_EXTENSIONS_BUILD',
  },
  { prefix: CURRENT_APP_NAME, scope },
);
