import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils'

const scope = "/Components/pages/Cap/"

export const actionTypes = defineActionTypes(
  {
    GET_SIDEBAR_MENU_DATA_REQUEST: "GET_SIDEBAR_MENU_DATA_REQUEST",
    GET_SIDEBAR_MENU_DATA_SUCCESS: "GET_SIDEBAR_MENU_DATA_SUCCESS",
    GET_SIDEBAR_MENU_DATA_FAILURE: "GET_SIDEBAR_MENU_DATA_FAILURE",
    CLEAR_SIDEBAR_MENU_DATA: "CLEAR_SIDEBAR_MENU_DATA",
    GET_TOPBAR_MENU_DATA_REQUEST: "GET_TOPBAR_MENU_DATA_REQUEST",
    GET_TOPBAR_MENU_DATA_SUCCESS: "GET_TOPBAR_MENU_DATA_SUCCESS",
    GET_TOPBAR_MENU_DATA_FAILURE: "GET_TOPBAR_MENU_DATA_FAILURE",
    CLEAR_TOPBAR_MENU_DATA: "CLEAR_TOPBAR_MENU_DATA",
    GET_USER_DATA_REQUEST: "GET_USER_DATA_REQUEST",
    GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
    GET_USER_DATA_FAILURE: "GET_USER_DATA_FAILURE",
    SWITCH_ORG_REQUEST: "SWITCH_ORG_REQUEST",
    SWITCH_ORG_SUCCESS: "SWITCH_ORG_SUCCESS",
    SWITCH_ORG_FAILURE: "SWITCH_ORG_FAILURE",
    GET_SUPPORTED_LOCALES_REQUEST: "GET_SUPPORTED_LOCALES_REQUEST",
    GET_SUPPORTED_LOCALES_SUCCESS: "GET_SUPPORTED_LOCALES_SUCCESS",
    GET_SUPPORTED_LOCALES_FAILURE: "GET_SUPPORTED_LOCALES_FAILURE",
  },
  { prefix: CURRENT_APP_NAME, scope: scope },
);

export const SIDEBAR_MENU_ITEM_POSITION = 'left';
export const ORG_SETTINGS_URL = '/org/index';
export const HELP_URL = 'https://support.capillarytech.com/en/support/solutions/97443';

export const getSettingsMenuData = () => [];

export const getTopbarMenuDataValue = () => [];
