import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils';

export const REDUCER_KEY = `${CURRENT_APP_NAME}_bugsnagIssueListing`;

const scope = '/Components/organisms/BugsnagIssueListing/';

export const actionTypes = defineActionTypes(
  {
    GET_APPLICATIONS_REQUEST: 'GET_APPLICATIONS_REQUEST',
    GET_APPLICATIONS_SUCCESS: 'GET_APPLICATIONS_SUCCESS',
    GET_APPLICATIONS_FAILURE: 'GET_APPLICATIONS_FAILURE',

    GET_BUGSNAG_ISSUES_REQUEST: 'GET_BUGSNAG_ISSUES_REQUEST',
    GET_BUGSNAG_ISSUES_SUCCESS: 'GET_BUGSNAG_ISSUES_SUCCESS',
    GET_BUGSNAG_ISSUES_FAILURE: 'GET_BUGSNAG_ISSUES_FAILURE',

    UPDATE_BUGSNAG_ERROR_STATUS_REQUEST: 'UPDATE_BUGSNAG_ERROR_STATUS_REQUEST',
    UPDATE_BUGSNAG_ERROR_STATUS_SUCCESS: 'UPDATE_BUGSNAG_ERROR_STATUS_SUCCESS',
    UPDATE_BUGSNAG_ERROR_STATUS_FAILURE: 'UPDATE_BUGSNAG_ERROR_STATUS_FAILURE',
  },
  { prefix: CURRENT_APP_NAME, scope },
);
