export const VULCAN_APPS = [
  { value: 'all', label: 'All Products' },
  { value: 'loyalty-engine', label: 'Loyalty Engine' },
  { value: 'campaign-manager', label: 'Campaign Manager' },
  { value: 'insights-plus', label: 'Insights+' },
  { value: 'engage-plus', label: 'Engage+' },
  { value: 'member-care', label: 'Member Care' },
];

export const DUMMY_ISSUES = [
  {
    key: '1',
    details: 'TypeError: Cannot read properties of undefined (reading "map")',
    events: 1247,
    users: 312,
    severity: 'error',
    lastSeen: '2026-04-12 14:32:10',
  },
  {
    key: '2',
    details: 'NetworkError: Failed to fetch /api/v2/loyalty/points',
    events: 893,
    users: 201,
    severity: 'error',
    lastSeen: '2026-04-12 14:28:45',
  },
  {
    key: '3',
    details: 'Warning: Each child in a list should have a unique "key" prop',
    events: 2451,
    users: 589,
    severity: 'warning',
    lastSeen: '2026-04-12 13:55:22',
  },
  {
    key: '4',
    details: 'RangeError: Maximum call stack size exceeded in CampaignTree',
    events: 156,
    users: 42,
    severity: 'error',
    lastSeen: '2026-04-12 12:10:08',
  },
  {
    key: '5',
    details: 'Unhandled promise rejection: Request timeout after 30000ms',
    events: 534,
    users: 178,
    severity: 'warning',
    lastSeen: '2026-04-12 11:47:33',
  },
  {
    key: '6',
    details: 'SyntaxError: Unexpected token < in JSON at position 0',
    events: 321,
    users: 95,
    severity: 'error',
    lastSeen: '2026-04-11 23:15:01',
  },
  {
    key: '7',
    details: 'Info: Deprecated API endpoint /v1/members called',
    events: 4120,
    users: 1023,
    severity: 'info',
    lastSeen: '2026-04-11 22:40:19',
  },
  {
    key: '8',
    details: 'ChunkLoadError: Loading chunk 14 failed (missing: /static/js/14.chunk.js)',
    events: 87,
    users: 31,
    severity: 'error',
    lastSeen: '2026-04-11 19:22:55',
  },
];
