import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils';

export const DEBOUNCE_MS = 300;

export const REDUCER_KEY = `${CURRENT_APP_NAME}_dbAuditLog`;

const scope = '/Components/organisms/DBAuditLog/';

export const actionTypes = defineActionTypes(
  {
    GET_MONGO_AUDIT_LOGS_REQUEST: 'GET_MONGO_AUDIT_LOGS_REQUEST',
    GET_MONGO_AUDIT_LOGS_SUCCESS: 'GET_MONGO_AUDIT_LOGS_SUCCESS',
    GET_MONGO_AUDIT_LOGS_FAILURE: 'GET_MONGO_AUDIT_LOGS_FAILURE',
    GET_MONGO_AUDIT_LOG_DETAIL_REQUEST: 'GET_MONGO_AUDIT_LOG_DETAIL_REQUEST',
    GET_MONGO_AUDIT_LOG_DETAIL_SUCCESS: 'GET_MONGO_AUDIT_LOG_DETAIL_SUCCESS',
    GET_MONGO_AUDIT_LOG_DETAIL_FAILURE: 'GET_MONGO_AUDIT_LOG_DETAIL_FAILURE',
    CLEAR_MONGO_AUDIT_LOG_DETAIL: 'CLEAR_MONGO_AUDIT_LOG_DETAIL',

    APPROVE_MONGO_AUDIT_LOG_REQUEST: 'APPROVE_MONGO_AUDIT_LOG_REQUEST',
    APPROVE_MONGO_AUDIT_LOG_SUCCESS: 'APPROVE_MONGO_AUDIT_LOG_SUCCESS',
    APPROVE_MONGO_AUDIT_LOG_FAILURE: 'APPROVE_MONGO_AUDIT_LOG_FAILURE',

    REJECT_MONGO_AUDIT_LOG_REQUEST: 'REJECT_MONGO_AUDIT_LOG_REQUEST',
    REJECT_MONGO_AUDIT_LOG_SUCCESS: 'REJECT_MONGO_AUDIT_LOG_SUCCESS',
    REJECT_MONGO_AUDIT_LOG_FAILURE: 'REJECT_MONGO_AUDIT_LOG_FAILURE',
  },
  { prefix: CURRENT_APP_NAME, scope },
);

export const STATUS_OPTIONS = [
  { key: 'all', label: 'All Statuses', value: 'all' },
  { key: 'PENDING_APPROVAL', label: 'Pending Approval', value: 'PENDING_APPROVAL' },
  { key: 'SUCCESS', label: 'Success', value: 'SUCCESS' },
  { key: 'FAILED', label: 'Failed', value: 'FAILED' },
  { key: 'REJECTED', label: 'Rejected', value: 'REJECTED' },
];
